name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        env: 
          api_key: ${{ secrets.CYPRESS_MAILSLURP_API_KEY }}
          run: echo  "::set-output name=api_key::${{ env.api_key }}"
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          node-version: 18
       